version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    container_name: frontend
    restart: always
    links:
      - backend

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    container_name: backend
    restart: always