name: CI

on:
  push:
    branches: [ master ]
  
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Testing
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup Testing Env.
      run: make build_test
    
    - name: Run Tests
      run: make run_test


  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: <your repo name>/<your application name>:latest
